# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: CPREgroup
# Description of the Site
description: Computational Photography Research & Engineering
# URL of Image of the Site
site-image: assets/images/logo.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: assets/images/background.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1136954568@qq.com
#facebook_username: thedevslot
twitter_username: python
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username: CPREgroup
google_email: xinyuchen970@gmail.com
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Yuqi Li
# URL for the Image of the Author
author-image: assets/images/user.jpg
# 60 Words About the Author
author-about: 目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。目前从事的主要研究工作：研究领域包括深度学习，图像处理，计算摄影，计算显示。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/CPREgroup

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      author: "Yuqi Li"
      author-link: "/"
      selected: false
      type: "blog"
      tags:
        - ""
  - scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
